# -*- coding: utf-8 -*-
"""NumPY_Assesment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ri_dVD3yOUkMmMM2B9hASUn6LJEE14yD
"""

# 1) Import pandas and read in the banklist.csv file into a dataframe called banks.
import numpy as np
import pandas as pd

df=pd.read_csv("/content/banklist.csv")
# 2) Show the head of the dataframe.

print(df.head())

# 3) What are the column names?
df.columns

# 4) How many States (ST) are represented in this data set?
unique_states = df['ST'].nunique()

print("Number of unique states represented:", unique_states)

# 5) Get a list or array of all the states in the data set.
all_states = df['ST'].values
print("All states (array form):", all_states)

# 6) What are the top 5 states with the most failed banks?
top_5_states = df['ST'].value_counts().head(5)
print([top_5_states])

# 7) What are the top 5 acquiring institutions?
top_5_acquirers = df['Acquiring Institution'].value_counts().head(5)
print([top_5_acquirers])

# 8) How many banks has the State Bank of Texas acquired? How many of
# them were actually in Texas?
texas_acquisitions = df[df['Acquiring Institution'] == 'State Bank of Texas']
print([texas_acquisitions])

# 9) What is the most common city in California for a bank to fail in?
california_banks = df[df['ST'] == 'CA']
print([california_banks])